### ISSUE TITLE
getAge gives wrong age

### ISSUE THREAD

**Issue by rasmusbe** [personnummer/js#20]
Born 1964, birthday yesterday (should be 55 years)
![image](https://user-images.githubusercontent.com/2124386/68867548-50783c80-06f6-11ea-8d96-bbd3c00f9025.png)

Born 1964, birthday today (should be 55 years)
![image](https://user-images.githubusercontent.com/2124386/68867266-d647b800-06f5-11ea-990b-e620493506bd.png)

Born 1964, birthday tomorrow
![image](https://user-images.githubusercontent.com/2124386/68867642-7a316380-06f6-11ea-81e9-eab3a179e8c0.png)

Everyone gets the same age

**Comment by frozzare** [comment]
Fixed 2.1.1.
