### ISSUE TITLE
Temporary Personal Numbers

### ISSUE THREAD

**Issue by endri55** [personnummer/js#211]
Hi Guys!

Nice small project you guys built here.
I was wondering if you have intentionally left the temporary personal numbers out or this is something you haven't taken into consideration?

An input of YYYYMMDD**T**XXX / YYMMDD**T**XXX should actually be true, the way you can simply fix this and support temporary personal numbers is to check if there is a T and replace that with 1 before you make the validation check. We currently do this in code before we check for validation and it's not a big deal however it would be nice if it's implemented in this project by default.

Thank you!

**Comment by Johannestegner** [comment]
Hi there @endri55 !

When it comes to temporary ones, the system have changed to "samordningsnummer" (coordination numbers), I'm not sure if there are anyone who have a tilldelningsnummer in Sweden as of now?
Now, I have only done some quick checks for it, so if you have any sources which shows it as something actually used still in any way, I'll gladly propose it as an option in the api specification :)

**Comment by endri55** [comment]
Hi @Johannestegner,

The temporary number is still widely used for students in Sweden.

`The personal identity number issued by the Tax Agency should not be confused with the temporary registration number, a 4-digit number following your date of birth containing the letter ‘T’, given to you by KTH when you were admitted. Format of T-number: YYMMDD-TXXX`

Source: https://www.kth.se/en/student/studentliv/new-in-sweden/swedish-personal-identity-number-1.443883

Our solution for this is by simply replacing the T with 1 and then it works fine with the verifier.

`str.replace("T", "1")`
Before passing it onto the other function to verify should do the trick.

**Comment by frozzare** [comment]
@endri55 Hey, sorry for the late answer, i've started to look into this and it's not hard to fix and we should probably do it. The hard part is to find some valid TP-numbers that can be public and that we can use for our tests. Do you know any numbers that we can use? 

I've also tried to search GitHub for other personnummer packages and see how they do with TP-numbers and haven't found any package that actual implemented this and then I didn't found any testdata. 

We have this folder of testdata where we would like to add test TP-numbers https://github.com/personnummer/meta/tree/master/testdata

**Comment by frozzare** [comment]
Moving this discussion to meta repository since it will not just be a change in the JavaScript package https://github.com/personnummer/meta/issues/43
