### ISSUE TITLE
[BUG] - .format() adds "+" instead of "-" in specific case

### ISSUE THREAD

**Issue by Hannessa** [personnummer/js#212]
Hi. When I run the following code:

```
var Personnummer = require('personnummer');

Personnummer.parse("19101010-1010").format()
```

I expect to get "101010-1010" back, but I actually get "101010+1010". If I omit "19" it seems to work correctly, and other personal numbers seem to work fine.

Any idea why it's returning "+" instead of "-"?

Personal number "19101010-1010" is often used for testing, so that's why I'm using it. And it makes me a bit afraid it might happen in other cases as well.

Thanks!

**Comment by frozzare** [comment]
Hey, 

When you are over 100 years old you should use `+` sign instead of `-` and we try to figure out which sign to use and for this case it works as expected.

**Comment by Hannessa** [comment]
Ahhh, thanks for the information, I did not know this. You're correct, I see this when I Google now. I just assumed it was a bug because I hadn't heard of it before. Thanks for clarifying! And thanks for the great library.
