### ISSUE TITLE
private fields are stage-3 and not ready for production use

### ISSUE THREAD

**Issue by iamstarkov** [personnummer/js#22]
[all private fields and methods proposals are at stage 3](https://github.com/tc39/proposals), but we are interested in https://github.com/tc39/proposal-private-methods.

According to the [TC39 Process document](https://tc39.es/process-document/), stage 3 indicates "further refinement will require feedback from implementations and users".

To make things more problematic last time all three proposals had been presented and discussed were a year ago (January 2019).

I would suggest to not utilize this proposal in the code intended for production use, until the proposal lands on stage 4.

**Comment by Johannestegner** [comment]
Hi there @iamstarkov!

The private methods used in the code are only in the source code, not in the produced files which are used when aquireing the package from npm similar.
So if it's the source you are referring to, this will stay as is until the feature is changed (or added to ecma standard), if they have slipped through into the "compiled" code, please let ping me or @frozzare and we will take a look at the build scripts!

**Comment by iamstarkov** [comment]
No problem with distributed code, its fine.

The problem with non-stage-4 is that these proposals can be withdrawn and/or cancelled at any time. Or even a complete non-backwards compatible spec rewrite can happen. Cancellable Promises and Class Decorators are among those unfortunate examples.

In other risks, contributors' onboarding can be slower than without non-stage-4 proposals too.

**Comment by frozzare** [comment]
Thanks for your concern, if it will be withdraw we'll change. But for now we will keep private methods as it is. 

Looking at the TC39 repo we can see other bigger project that has implemented support for private methods, like V8. It's not a big issue for a small project like us to change fast.
