### ISSUE TITLE
[BUG] - Sammordningsnummer fungerar inte

### ISSUE THREAD

**Issue by mortb** [personnummer/js#223]
Vi tar allas favorittestpersonnummer:

`Personnummer.valid("121212-1212");  // => true`

Enligt spec ska man lägga på 60 på dagen för att få ett samordningsnummer vilket borde bli dagnummer 72, 
men...

`Personnummer.valid("121272-1212");  // => false`

Verkar vara en bugg att sista kodsnutten ger `false`, eller missar jag något här?

**Comment by frozzare** [comment]
Hej,

Det går inte att lägga till 60 dagar bara sådär utan att ändra sista siffran med. Ett personnummer kan inte vara både ett personnummer och samordningsnummer samtidigt :)

Stänger ärendet då det inte är någon bugg.

**Comment by mortb** [comment]
Aha...ja, det förstås. Naturligtvis behöver jag en ny kontrollsiffra. Tack!
