### ISSUE TITLE
babel and core dont belong to dependencies but devDependencies

### ISSUE THREAD

**Issue by iamstarkov** [personnummer/js#23]
I believe its proper devDependencies and not dependencies. https://github.com/personnummer/js/blob/master/package.json#L24-L28

Maybe I misunderstand something, so is there any particular reasoning behind babel and core in dependencies?

**Comment by Johannestegner** [comment]
You are right, will fix ASAP.

Thank you!

**Comment by frozzare** [comment]
Fixed in [3.0.1](https://github.com/personnummer/js/releases/tag/v3.0.1). Thanks for the bug report!

**Comment by iamstarkov** [comment]
yay, thank you
