### ISSUE TITLE
[BUG] - `this._sep` not set when parsing short-form numbers for people aged 100+

### ISSUE THREAD

**Issue by swantzter** [personnummer/js#60]
**Context**

In the if statement on line 199 this._sep is not being set set when the separator is `+` (line 203-204) like it is for `-` on line 206. this means `instance.format()` gives the wrong output.

https://github.com/personnummer/js/blob/ded2eb7046bd712a633efcd9ecc6ebcca2da6777/src/index.ts#L199-L214

Furthermore `this._century` is set on line 210, but `century` (declared on line 192) is not reassigned, which causes problems on line 225 where `century` rather than `this._century` where `this.fullYear` is set to `century + year` resulting in the year of `undefined09`

https://github.com/personnummer/js/blob/ded2eb7046bd712a633efcd9ecc6ebcca2da6777/src/index.ts#L224-L229

**Expected outcome**

```javascript
new Personnummer('090527+1474')
> Personnummer {
  _century: '19',
  _fullYear: '1909',
  _year: '09',
  _month: '05',
  _day: '27',
  _sep: '+',
  _num: '147',
  _check: '4'
}
```

**Actual outcome**

```javascript
new Personnummer('090527+1474')
> Personnummer {
  _century: '19',
  _fullYear: 'undefined09',
  _year: '09',
  _month: '05',
  _day: '27',
  _sep: '',
  _num: '147',
  _check: '4'
}
```

**Comment by Johannestegner** [comment]
Thank you for the contribution! :)
