### ISSUE TITLE
[BUG] - Incorrect validation  

### ISSUE THREAD

**Issue by VovaChampion** [personnummer/js#671]
**Context**

I use the latest version 3.2.1 i react project 

Noticed that some personal nummers goes through validation form as valid, but it's not.
For ex: 20021090-5311

According to description  _"Det består av födelsedatum (ååmmdd), följt av fyra siffror."_  **90** cannot be a day of a month

**Expected outcome**

false

**Actual outcome**

true

**Description**

**Minimal reproducible test case**

 console.log(Personnummer.valid("20021090-5311")); // true

**Comment by frozzare** [comment]
Hi,

This is a [Samordningsnummer](https://sv.wikipedia.org/wiki/Personnummer_i_Sverige#Samordningsnummer_och_organisationsnummer) where the days can contain +60, so 90-60=30.

This can be disabled, with the options ´allow`

```
const Personnummer = require("personnummer");

const options = {
  allowCoordinationNumber: false,
};
console.log(Personnummer.valid("INPUT", options));
```

**Comment by VovaChampion** [comment]
Aha, thank you! Didn't know about Samordningsnummer 👍
