### ISSUE TITLE
[BUG] - Wrong century when older than 100 years is parsing

### ISSUE THREAD

**Issue by fredrikmork** [personnummer/js#722]
**Context and Results**

OS is macOS Sonoma 14.5
VS Code version 1.92.0

I am expecting personnummer above 100 years to have correct century and date when invoking `Personnummer.parse(number).getDate() `and `Personnummer.parse(number).century`.

I am using the [swedish personnummer generator](https://tedeh.net/tools/generator-for-swedish-personnummer/) to generate a personnummer that is above 100 years. When I am parsing  `Personnummer.parse('2005281528').getDate()` i get the year 2020 instead of 1920.

_Disclaimer_: I dont know if these numbers are correct from "tedeh.com" when above 100 years.

<img width="998" alt="Skjermbilde 2024-08-06 kl  11 53 45" src="https://github.com/user-attachments/assets/99c90aa1-c2d4-4c83-aa89-0a7dd13f5594">

**Test case**

[Example on codeSandbox](https://codesandbox.io/p/devbox/personnummer-wrong-century-945vmd?file=%2Fsrc%2FApp.tsx%3A9%2C47)
<img width="1405" alt="Skjermbilde 2024-08-13 kl  09 52 18" src="https://github.com/user-attachments/assets/0b1050a8-672c-4365-90a0-70a85b400516">

**Comment by Johannestegner** [comment]
Hi!

When using an input without either separator (+/-) or century, the code have to guess, and we have decided to take the closest century in the parser.

So to be able to get the age/date of birth with accuracy, you would either have to use the long format (192005281528) or use a separator (200528+1528), where the separator version is the actual personnummer standard.

**Comment by fredrikmork** [comment]
Hi! Ok, thanks for such a quick response 🙏
